version: "3.9"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ~/.todd-coin/pg-data:/var/lib/postgresql/data
volumes:
  pg-data:
